import Head from "next/head";
import Nav from "@/components/nav";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import highlight from "highlight.js";
import { use, useEffect, useState } from "react";
import Image from "next/image";

export default function Home() {
  const scrollToClass = (className: string) => {
    const element = document.querySelector(`.${className}`) as HTMLElement;

    if (element) {
      const windowHeight = window.innerHeight;
      const elementHeight = element.offsetHeight;
      const offset = Math.max(0, (windowHeight - elementHeight) / 2);

      window.scrollTo({ top: element.offsetTop - offset, behavior: "smooth" });
    }
  };

  const fetchMovie = async () => {
    const responseElement = document.getElementById("response");
    if (responseElement) responseElement.innerHTML = "Fetching...";

    let titleElement = document.getElementById("film") as HTMLInputElement;
    let title = "Howl's Moving Castle";
    if (titleElement) title = titleElement.value;
    if (title.toLowerCase().includes("rick")) {
      titleElement.value = "rickroll";
      window.location.href =
        "https://open.spotify.com/intl-de/track/4cOdK2wGLETKBW3PvgPWqT?si=726fbabd4530461d";
    }
    const response = fetch(`https://ghibli.rest/films?search=${title}`)
      .then((res) => res.json())
      .then((data) => {
        setTimeout(() => {
          if (responseElement)
            responseElement.innerHTML = JSON.stringify(data, null, 2);
        }, 300);
      })
      .catch((err) => {
        if (responseElement) responseElement.innerHTML = "Failed to fetch";
      });
  };

  const fetchRandomMovie = async () => {
    const responseElement = document.getElementById("response");
    if (responseElement) responseElement.innerHTML = "Fetching...";

    const response = fetch(`https://ghibli.rest/films/random`)
      .then((res) => res.json())
      .then((data) => {
        setTimeout(() => {
          if (responseElement)
            responseElement.innerHTML = JSON.stringify(data, null, 2);
        }, 300);
      })
      .catch((err) => {
        if (responseElement) responseElement.innerHTML = "Failed to fetch";
      });
  };

  useEffect(() => {
    fetchRandomMovie();
  }, []);

  useEffect(() => {
    const responseElement = document.getElementById("response");
    if (responseElement) responseElement.innerHTML = "Fetching...";
  });

  return (
    <>
         
      <Head>
        <title>ghibli.rest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${styles.main}`}>
        <Nav />
        <div className={`${styles.welcome}`}>
          <div className={`${styles.text}`}>
            <h1>ghibli.rest</h1>
            <p>
              Explore the Magical World of Studio Ghibli with ghibli.rest, the
              API and Discord Bot for All Studio Ghibli Enthusiasts
            </p>
            <div className={`${styles.buttons}`}>
              <Link href="https://docs.ghibli.rest" className={`${styles.button}`}>
                Documentation
              </Link>
            </div>
          </div>
          <Image
            src="/welcome2.png"
            width={449}
            height={520}
            alt=""
            draggable={false}
          ></Image>
        </div>

        <div className={`${styles.demo} demo`}>
          <div className={`${styles.info}`}>
            <h3>Demo</h3>
            <p>Search for any Ghibli movie title</p>
            <div>
              <input
                type="text"
                placeholder="Film Title"
                id="film"
                onKeyUp={(e) => fetchMovie()}
              />
              {/* <i onClick={() => fetchMovie()} className={"bx bx-search"}></i> */}
              <i
                onClick={() => fetchRandomMovie()}
                className={"bx bx-cube-alt"}
              ></i>
            </div>
          </div>
          <div className={`${styles.response}`}>
            <p>Response</p>
            <pre id="response"></pre>
          </div>
        </div>
      </main>
    </>
  );
}
