import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import highlight from "highlight.js";
import { use, useEffect } from "react";

export default function Home() {
  const scrollToClass = (className: string) => {
    const element = document.querySelector(`.${className}`) as HTMLElement;

    if (element) {
      const windowHeight = window.innerHeight;
      const elementHeight = element.offsetHeight;
      const offset = Math.max(0, (windowHeight - elementHeight) / 2);

      window.scrollTo({ top: element.offsetTop - offset, behavior: "smooth" });
    }
  };

  const fetchMovie = async () => {
    let titleElement = document.getElementById("film") as HTMLInputElement;
    let title = "Howl's Moving Castle";
    if (titleElement) title = titleElement.value;
    const response = await fetch(`http://localhost:6543/films?search=${title}`);
    const data = await response.json();

    const responseElement = document.getElementById("response");
    if (responseElement)
      responseElement.innerHTML = JSON.stringify(data, null, 2);
  };

  useEffect(() => {
    fetchMovie();
  }, []);

  useEffect(() => {
    const code = document.getElementById("response");
    if (code !== null) {
      code.innerHTML = JSON.stringify(
        [
          {
            id: "cd3d059c-09f4-4ff3-8d63-bc765a5184fa",
            title: "Howl's Moving Castle",
            original_title: "ハウルの動く城",
            original_title_romanised: "Hauru no ugoku shiro",
            image:
              "https://image.tmdb.org/t/p/w600_and_h900_bestv2/TkTPELv4kC3u1lkloush8skOjE.jpg",
            movie_banner:
              "https://image.tmdb.org/t/p/original/hjlvbMKhQm7N8tYynr8yQ8GBmqe.jpg",
            description:
              "When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking home.",
            director: "Hayao Miyazaki",
            producer: "Toshio Suzuki",
            release_date: "2004",
            running_time: "119",
            rt_score: "87",
            people: ["https://ghibli.rest/people/"],
            species: [
              "https://ghibli.rest/species/af3910a6-429f-4c74-9ad5-dfe1c4aa04f2",
            ],
            locations: ["https://ghibli.rest/locations/"],
            vehicles: ["https://ghibli.rest/vehicles/"],
            url: "https://ghibli.rest/films/cd3d059c-09f4-4ff3-8d63-bc765a5184fa",
          },
        ],
        null,
        2
      );
    }
  });

  return (
    <>
      <Head>
        <title>ghibli.rest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${styles.main}`}>
        <nav>
          <div className={`${styles.title}`}>
            <Image src="/logo.png" alt="" width={42} height={42}></Image>
            <h1>ghibli.rest</h1>
          </div>
          <div className={`${styles.links}`}>
            <Link href="/">Home</Link>
            <a onClick={() => scrollToClass("demo")}>Demo</a>
            <a>Stats</a>
            <Link href="/docs">Docs</Link>
            <Link
              href="https://donate.ghibli.rest"
              className={`${styles.donate}`}
            >
              Donate
            </Link>
          </div>
        </nav>

        <div className={`${styles.welcome}`}>
          <h1>ghibli.rest</h1>
          <p>
            Explore the Magical World of Studio Ghibli with ghibli.rest, the
            Discord Bot for All Ghibli Enthusiasts
          </p>
          <div className={`${styles.buttons}`}>
            <a
              onClick={() => scrollToClass("demo")}
              className={`${styles.button}`}
            >
              Demo
            </a>
            <Link href="/docs" className={`${styles.button}`}>
              Documentation
            </Link>
          </div>
        </div>

        <div className={`${styles.demo} demo`}>
          <div className={`${styles.info}`}>
            <h3>Demo</h3>
            <p>Search for any Ghibli movie title</p>
            <div>
              <input
                type="text"
                placeholder="Film Title"
                id="film"
                defaultValue="Howl's Moving Castle"
                onKeyUp={(e) => fetchMovie()}
              />
              <i onClick={() => fetchMovie()} className={"bx bx-refresh"}></i>
              <i className={"bx bx-cube-alt"}></i>
            </div>
          </div>
          <div className={`${styles.response}`}>
            <p>Response</p>
            <pre id="response"></pre>
          </div>
        </div>
      </main>
    </>
  );
}
